region: eu-west-1
hostport: 80
containerport: 80
role: backend-apps
environment: prod
iac: terraform-workspace-aws-prod-applications-eu-west-1-apps-auto-claim-zkevm-testnet-auto-claim
team_name: product-apps
memory: 1024
cpu: 512
env_vars:
  - name: NETWORK
    value: testnet
  - name: TRANSACTIONS_URL
    value: https://api-gateway.polygon.technology/api/v3/transactions/testnet
  - name: PROOF_URL
    value: https://api-gateway.polygon.technology/api/v3/proof/testnet/merkle-proof
  - name: CLAIM_COMPRESSOR_CONTRACT
    value: "0xcb8b435481dA1eD5ABC895e03535ce0Bba3b6905"
  - name: BRIDGE_CONTRACT
    value: "0x528e26b25a34a4A5d0dbDa1d57D318153d2ED582"
  - name: GAS_STATION_URL
    value: https://gasstation.polygon.technology/zkevm/cardona
  - name: SOURCE_NETWORKS
    value: "[0]"
  - name: DESTINATION_NETWORK
    value: "1"
  - name: NODE_ENV
    value: prod
secret_vars:
  - PRIVATE_KEY
  - RPC_URL
  - SLACK_URL
  - SENTRY_DSN
  - SOURCE_NETWORKS_RPC
