name: Auto Claim Deployment
on:
  push:
    branches:
      - DEVOPS-2801-auto-claim-deployment
  workflow_dispatch:
    inputs:
      environment:
        required: false
        type: choice
        description: "Select the environment to deploy to (optional for pushes)"
        options:
          - prod

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      environment: ${{ inputs.environment || 'staging' }}
      core_app: "auto-claim"
    secrets: inherit
