name: Zkevm mainnet Auto Claim ZKEVM Deployment Prod
on:
  push:
    branches:
      - batch-claim
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      environment: 'prod'
      core_app: "zkevm-mainnet-auto-claim"
    secrets: inherit
